### ISSUE TITLE
在浏览吧内帖子静置时窗口surface持续刷新

### ISSUE THREAD

**Issue by UISSD** [HuanCheng65/TiebaLite#101]
系统MIUI13 13.0.16 稳定版 机型redmi k50
如图，在吧首页顶部静止时不会出现窗口surface持续刷新情况，此时可从fps监视器中看到此时fps为0
![Screenshot_2022-05-24-22-18-07-269_com huanchengfly tieba post](https://user-images.githubusercontent.com/36440730/170058624-b8fe9da8-2291-40fa-9041-178477607195.jpg)
往下滑动，在某处停止。虽然此时画面是静态的，但实际上系统一直在刷新画面，从fps监视器可看到此时fps为120
![Screenshot_2022-05-24-22-18-17-405_com huanchengfly tieba post](https://user-images.githubusercontent.com/36440730/170058653-b39ffd42-a1f6-4032-bf70-466583812bf8.jpg)
复现概率有90%，这个bug会导致浏览静态页面时耗电过高，比正常电流多一倍左右

**Comment by 5ec1cff** [comment]
![image](https://user-images.githubusercontent.com/56485584/175356240-63ad00e2-2ac2-4646-997f-91f1b29f4de6.png)


问题似乎在这里：[ForumActivity](https://github.com/HuanCheng65/TiebaLite/blob/4.0-dev/app/src/main/java/com/huanchengfly/tieba/post/activities/ForumActivity.kt#L273) 中，当贴吧信息卡片的吧名划过 ToolBar 后会修改 Activity 的标题，以在 Toolbar 上显示或隐藏吧名。然而修改标题会触发 View 树更新，又导致图中的 appbar 的 OnOffsetChangedListener 触发（虽然 offset 并没有改变），修改标题，于是陷入了死循环，View 树不断更新。移除这段代码后就不会出现问题，不过没法实现原本的效果。

在 ThreadActivity 中有类似的设计，不过更新标题的过程放在了 OnScroll 中，这样就不会导致死循环。

**Comment by HuanCheng65** [comment]
> ![image](https://user-images.githubusercontent.com/56485584/175356240-63ad00e2-2ac2-4646-997f-91f1b29f4de6.png)
> 
> 问题似乎在这里：[ForumActivity](https://github.com/HuanCheng65/TiebaLite/blob/4.0-dev/app/src/main/java/com/huanchengfly/tieba/post/activities/ForumActivity.kt#L273) 中，当贴吧信息卡片的吧名划过 ToolBar 后会修改 Activity 的标题，以在 Toolbar 上显示或隐藏吧名。然而修改标题会触发 View 树更新，又导致图中的 appbar 的 OnOffsetChangedListener 触发（虽然 offset 并没有改变），修改标题，于是陷入了死循环，View 树不断更新。移除这段代码后就不会出现问题，不过没法实现原本的效果。
> 
> 在 ThreadActivity 中有类似的设计，不过更新标题的过程放在了 OnScroll 中，这样就不会导致死循环。

解决了，加入了一个 titleVisible 变化的判断，避免重复更新
