### ISSUE TITLE
帖子 Activity 重建时无法加载内容

### ISSUE THREAD

**Issue by 5ec1cff** [HuanCheng65/TiebaLite#110]
当 ThreadActivity 重建（如系统切换深色主题时）后会一直转圈，无法加载帖子内容。
我在自己的分支修复了一下这个问题，供参考（因为改了太多所以不 PR 了）：
https://github.com/5ec1cff/TiebaLite/commit/d5e98f91955bdfdb222c482e18c95d4b0dcb5f94

**Comment by HuanCheng65** [comment]
感谢！
