### ISSUE TITLE
大佬您好！

### ISSUE THREAD

**Issue by EarzuChan** [HuanCheng65/TiebaLite#111]
最近一直在使用您的项目，总体而言用户体验非常棒！
我自己在学C#，想仿造者您的项目做一个贴吧Uwp三端，但是在WebApi这些方面不太了解，您代码中对于Api的操作我也是一知半解地，所以方便的话可以加个联系方式（QQ2421565269、微信EARZUC（推荐您加我微信））吗？我想向您讨教一些账号登录和相关数据解析的操作！
谢谢大佬！

**Comment by EarzuChan** [comment]
通过多次阅读大佬的代码，我已经了解了如何创建和使用WebApi，谢谢大佬代码的公开

**Comment by EarzuChan** [comment]
不好意思！但是我这边本来想仿写您抓取关注贴吧列表的代码，可是我在C#里面配置了Header和Param等等，然后向代码中的uri发Post，得到的Json始终都是Error：未知错误，请问我该怎么办？方便加个联系方式讨论一下吗？

**Comment by n0099** [comment]
什么 https://github.com/EarzuChan/TiebaLiteUiInXaml
您就是`贴吧辅助工具头子`[鸡血神](https://github.com/bakasnow)？

**Comment by EarzuChan** [comment]
> 什么 https://github.com/EarzuChan/TiebaLiteUiInXaml
> 您就是`贴吧辅助工具头子`[鸡血神](https://github.com/bakasnow)？

不是
