### ISSUE TITLE
提点小功能，不知道能不能实现

### ISSUE THREAD

**Issue by wyy159** [HuanCheng65/TiebaLite#115]
1.缓存功能，在退出贴子后，如果不进入新的帖子而是返回原来那个帖子会直接回到对应楼层，无需加载，官方贴吧有的功能。
2.点赞功能，不知道为啥好像不能点赞，是我没找到怎么操作吗。
3.进入帖子后会有小圆圈加载，感觉比较慢，不知道可否优化一下，把小圆圈改成骨架页感觉也会好点。
最后感谢作者大大开发的这款产品，真的很好，很轻量，很流畅，比官方的流畅多了，还没广告，我就是因为官方贴吧经常滑动卡顿，受不了了，百度搜了一下，就找到了这个，真的很不错，有空看看源码，学习下。

**Comment by HuanCheng65** [comment]
2和3已完成，1计划中
