### ISSUE TITLE
在原贴吧APP里改了昵称，而且已过审核，但在贴吧lite里还是原来的昵称，退出账号重新登陆和清除APP数据再登陆都没用，这是BUG吗？

### ISSUE THREAD

**Issue by fengyulong01** [HuanCheng65/TiebaLite#117]
在原贴吧APP里改了昵称，而且已过审核，但在贴吧lite里还是原来的昵称，退出账号重新登陆和清除APP数据再登陆都没用，这是BUG吗？

**Comment by HuanCheng65** [comment]
是由于 App 采用的 API 版本导致的，后续会优化

**Comment by n0099** [comment]
https://github.com/Starry-OvO/aiotieba/issues/91#issuecomment-1404307422
