### ISSUE TITLE
[功能请求]吧务管理功能

### ISSUE THREAD

**Issue by zhenchao** [HuanCheng65/TiebaLite#12]
我很喜欢这个app，但我同时也是一个贴吧的吧务，日常使用软件的时候经常看到一些不符合吧规的内容，这时如果我想要执行吧务权限删帖封禁就需要切换到网页版，体验非常割裂，所以希望可以添加吧务功能的支持。

**Comment by HuanCheng65** [comment]
@zhenchao 暂时没有计划制作吧务管理，后续可能会加入
