### ISSUE TITLE
希望可以增加,显示'关注用户帖子'的页面或功能

### ISSUE THREAD

**Issue by Zhongheng-H** [HuanCheng65/TiebaLite#121]
不知道是不是我没有找到设置的地方,我想尝试让lite也像官方一样,可以显示已关注用户的实时最新帖子.不知道现在的版本有没有这个功能?没有的话,希望兄弟可以实现一下

**Comment by HuanCheng65** [comment]
@Zhongheng-H 没有，实现不了
