### ISSUE TITLE
改变切换侧边导航栏的条件

### ISSUE THREAD

**Issue by nothingshiru** [HuanCheng65/TiebaLite#126]
经测试发现需要宽、高同时大于599才会切换为侧边导航栏。侧边导航栏占用横向空间，切换条件不应受屏幕高宽影响。我建议把切换条件改为仅需宽度大于599，这样就能在手机横屏切换为侧边导航栏，把横屏时宝贵的纵向空间留给内容显示

**Comment by HuanCheng65** [comment]
@nothingshiru 你为什么要在手机上横过来用...
