### ISSUE TITLE
希望适配 Android 13 themed icon

### ISSUE THREAD

**Issue by txyyh** [HuanCheng65/TiebaLite#127]
https://developer.android.com/about/versions/13/features/#themed-app-icons
需要一个以灰度填充的 foreground icon

图省事的话，直接复制一份 foreground 改成灰度应该就行？

**Comment by HuanCheng65** [comment]
@txyyh 暂时不考虑适配，太丑

**Comment by txyyh** [comment]
那会接受pr吗
我可能会尝试改个灰度的foreground试试

**Comment by HuanCheng65** [comment]
@txyyh 主动开启的话倒是可以考虑下...

**Comment by HuanCheng65** [comment]
@txyyh pr接受的
