### ISSUE TITLE
楼中楼回复总是会报错

### ISSUE THREAD

**Issue by cantiandashu233** [HuanCheng65/TiebaLite#128]
![Screenshot_20220830_153411_com huanchengfly tieba post](https://user-images.githubusercontent.com/112489307/187443649-c652e48d-863e-44d7-b236-deb5fe0c1cd7.jpg)
![Screenshot_20220830_204744_com huanchengfly tieba post](https://user-images.githubusercontent.com/112489307/187443737-5963dd35-d1e8-4ddc-8cd7-2dd8c9171dbd.jpg)
手机是华为mate40pro，每次回复人家消息就算不带表情都有概率报错，我要崩溃了。。。

**Comment by HuanCheng65** [comment]
回贴相关问题不再接受反馈
