### ISSUE TITLE
优化进贴加载体验

### ISSUE THREAD

**Issue by nothingshiru** [HuanCheng65/TiebaLite#131]
进入帖子时需要等待整个页面加载，但是进入帖子前明明已经能看到帖子1楼的内容。请问有没有可能做到进贴时直接显示1楼内容？在阅读1楼内容的过程中加载评论，可以让人不会注意到评论加载过程，体验会更好。

**Comment by HuanCheng65** [comment]
@nothingshiru 不能

**Comment by HuanCheng65** [comment]
@nothingshiru 数据结构不一样
