### ISSUE TITLE
[BUG反馈]miui更新安装失败

### ISSUE THREAD

**Issue by mobeiCanyue** [HuanCheng65/TiebaLite#132]
好像是miui优化的问题，关闭了就能正常安装。
但是每次开关有点麻烦。大大可不可以miui发全量包更新呢

**Comment by D-Jancy** [comment]
你把下载链接复制下来，用浏览器打开，然后弹出下载下来的就是一个全量安装包，再直接安装就行

**Comment by mobeiCanyue** [comment]
> 你把下载链接复制下来，用浏览器打开，然后弹出下载下来的就是一个全量安装包，再直接安装就行

行我下次试试
