### ISSUE TITLE
疑似无法进入部分名称带特殊符号的吧

### ISSUE THREAD

**Issue by EastMonster** [HuanCheng65/TiebaLite#138]
版本：4.0.0.63.dev-11
我尝试进入 c++ 吧，搜索结果是可以正常显示的
![Screenshot_2022_1122_153732](https://user-images.githubusercontent.com/89259667/203253486-20dd51a3-0a7f-42e0-84ca-ad37bd2d0531.png)
但是点进去却是 c 吧。
![Screenshot_2022_1122_153805](https://user-images.githubusercontent.com/89259667/203253616-b26af742-fbb4-4a79-a329-a67b55b376b3.png)
即使是从“搜贴”选项中选择 c++ 吧的贴子，从贴子里的入口尝试进入 c++ 吧，最终也会进入 c 吧。
![入口指的是这个](https://user-images.githubusercontent.com/89259667/203253938-fc59e32d-ae52-44f8-9aef-99615dff4820.png)
个人判断这应该是一个 bug，希望可以得到修复，谢谢。

**Comment by EastMonster** [comment]
抱歉，刚刚用官方客户端进行同样操作也是同样的结果，打扰了。

**Comment by AegirVOD** [comment]
乐，侧面证明C > C++
