### ISSUE TITLE
为什么安装后 手机提示有恶意代码，要我卸载

### ISSUE THREAD

**Issue by f1900** [HuanCheng65/TiebaLite#139]
为什么安装后 手机提示有恶意代码，要我卸载

**Comment by tangfenga** [comment]
hxd，啥软件提醒的呀，我安装的谷歌套件，play商店那个扫描也没提醒我

**Comment by bilibili2233a** [comment]
国产手机手机管家特色功能:病毒查杀随便扫描应用

**Comment by f1900** [comment]
> 国产手机手机管家特色功能:病毒查杀随便扫描应用

我没装管家，三星手机 自带的安全检查

**Comment by f1900** [comment]
> hxd，啥软件提醒的呀，我安装的谷歌套件，play商店那个扫描也没提醒我

三星手机 自带的安全检查 https://tieba.baidu.com/p/7412917791

**Comment by 5ec1cff** [comment]
> > hxd，啥软件提醒的呀，我安装的谷歌套件，play商店那个扫描也没提醒我
> 
> 三星手机 自带的安全检查 ![3123b831e924b8998dc96e8c79061d950b7bf6ad](https://user-images.githubusercontent.com/13845980/204085970-bd472542-af5f-4e7d-a2f7-5543e7170be9.jpg)

~~你这三星手机的系统怎么那么像 MIUI~~

**Comment by HuanCheng65** [comment]
@f1900 请问是哪个版本，以及在哪里下载的？

**Comment by f1900** [comment]
> @f1900 请问是哪个版本，以及在哪里下载的？

3.8.3 就在这个仓库发行版那下的

**Comment by f1900** [comment]
> > > hxd，啥软件提醒的呀，我安装的谷歌套件，play商店那个扫描也没提醒我
> > 
> > 
> > 三星手机 自带的安全检查 ![3123b831e924b8998dc96e8c79061d950b7bf6ad](https://user-images.githubusercontent.com/13845980/204085970-bd472542-af5f-4e7d-a2f7-5543e7170be9.jpg)
> 
> ~你这三星手机的系统怎么那么像 MIUI~

这图我不是截的，别人跟我遇到一样的问题，别人的截图，提示是一样的

**Comment by HuanCheng65** [comment]
@f1900 3.8.3报毒是已知情况，忽略即可

**Comment by f1900** [comment]
> @f1900 3.8.3报毒是已知情况，忽略即可

3.8.1报毒吗，不报的话我用老版的

**Comment by HuanCheng65** [comment]
@f1900 旧版也可能会报的，报毒是由于签名问题

**Comment by f1900** [comment]
> @f1900 旧版也可能会报的，报毒是由于签名问题

可以修复吗

**Comment by latinisation** [comment]
三星确实会报恶意
![Screenshot_20221204_214911](https://user-images.githubusercontent.com/26472091/205494531-215eaef6-caac-48e0-9609-710d20683724.jpg)

**Comment by PRO-2684** [comment]
报毒逻辑：我不认识的都警告

**Comment by HuanCheng65** [comment]
@a2013025 下载到假的了吧
