### ISSUE TITLE
[bug]设置小尾巴后回贴会崩溃

### ISSUE THREAD

**Issue by WuJunkai2004** [HuanCheng65/TiebaLite#146]
我觉得小尾巴这个功能做的不错，挺有意思
但是设置小尾巴后，对帖子的回复会崩溃。比如有人回复2楼，我回复这个楼中楼的时候程序就会崩溃
我推测是回帖只能是单行文本，但是小尾巴会换行后加在内容后面

希望能修复

**Comment by WuJunkai2004** [comment]
我找到出现问题的代码了，过几天看看前后文有没有能try and catch 点地方

**Comment by n0099** [comment]
#147

**Comment by WuJunkai2004** [comment]
惊讶地发现有4.0的dev版，准备推一个PR到dev版过去
