### ISSUE TITLE
夜间模式会把图片变暗，要点开才正常显示，希望能加个选项

### ISSUE THREAD

**Issue by xzxz520cs** [HuanCheng65/TiebaLite#158]
![Screenshot_2023-02-16-16-48-58-53_48be6add0731f4739c7a8d5cfaea8079](https://user-images.githubusercontent.com/22582356/219316125-a32b1e49-91fc-4604-a15f-009dfbc101b9.jpg)
![Screenshot_2023-02-16-16-49-02-28_48be6add0731f4739c7a8d5cfaea8079](https://user-images.githubusercontent.com/22582356/219316144-1ec687a5-b7e6-44b1-b552-71f50dfd6cc7.jpg)
# #

**Comment by n0099** [comment]
这图有alpha通道（透明底）吧，那幻影坦克应该也会被夜间模式影响到

**Comment by xzxz520cs** [comment]
所有的图都这样的，幻影坦克其实也有显示问题吧。
![Screenshot_2023-02-17-09-40-33-07_48be6add0731f4739c7a8d5cfaea8079](https://user-images.githubusercontent.com/22582356/219528045-fe8116ca-4bd4-4997-b9d7-48d5ce2082ad.jpg)
![Screenshot_2023-02-17-09-41-07-32_48be6add0731f4739c7a8d5cfaea8079](https://user-images.githubusercontent.com/22582356/219528057-73c41070-54df-41cb-8f14-d7a2c8acb01c.jpg)
![Screenshot_2023-02-17-09-41-10-54_48be6add0731f4739c7a8d5cfaea8079](https://user-images.githubusercontent.com/22582356/219528067-f5183143-baef-41a8-9ea5-704a1d8eff22.jpg)
夜间和白天都会吧幻影和原图都显示

像这种明显是截图的也变暗了，碰到比较暗的图细节就全没了。
![Screenshot_2023-02-17-09-45-18-45_48be6add0731f4739c7a8d5cfaea8079](https://user-images.githubusercontent.com/22582356/219528614-1d925894-0866-4b40-a46e-619ce21cc259.jpg)

![Screenshot_2023-02-17-09-45-23-88_48be6add0731f4739c7a8d5cfaea8079](https://user-images.githubusercontent.com/22582356/219528626-fe8b0b02-b467-4ec3-8e2c-d89331168911.jpg)

**Comment by n0099** [comment]
疑似使用了作用于RGBA 4通道的伽马修正
https://en.wikipedia.org/wiki/Gamma_correction
https://www.cambridgeincolour.com/tutorials/gamma-correction.htm
试试这图（但它没有alpha）
[![](https://user-images.githubusercontent.com/13030387/219535328-5d89477f-d2fc-4094-912b-412b0116a82b.png)](https://en.wikipedia.org/wiki/File:Gamma_correction_test_picture.png)
> 测试图像需要像素精确显示。使用维基百科图片属性框和网络浏览器缩放 100%。3%/97%明度方格区域的平均明度在观察者眼中综合为50%明度。非方格区域亮度为 0.5^(1/gamma)。如果系统伽玛（操作系统、显卡、显示器）等于测试图像伽玛，格子和非格子区域具有相同的亮度。

**Comment by xzxz520cs** [comment]
![Screenshot_2023-02-17-11-33-54-73_48be6add0731f4739c7a8d5cfaea8079](https://user-images.githubusercontent.com/22582356/219543423-08bd569f-d18e-4612-95d6-009f63b6d0ac.jpg)
![Screenshot_2023-02-17-11-33-49-85_48be6add0731f4739c7a8d5cfaea8079](https://user-images.githubusercontent.com/22582356/219543437-da3bb5c3-5928-4865-b56a-7d6d6330c470.jpg)
![Screenshot_2023-02-17-11-36-15-91_48be6add0731f4739c7a8d5cfaea8079](https://user-images.githubusercontent.com/22582356/219543448-7e36f8b6-3ea5-47dc-b7b4-f463acd8f9df.jpg)
白天模式也一样，这只是压了图吧？好像和变暗没关系

**Comment by HuanCheng65** [comment]
@xzxz520cs 夜间模式确实做了小图降低亮度
https://github.com/HuanCheng65/TiebaLite/blob/3ae3fcb96f854dcc5ad0b9c020a5504e0099ec61/app/src/main/java/com/huanchengfly/tieba/post/utils/ImageUtil.java#L496

**Comment by xzxz520cs** [comment]
总之就是希望能加个选项

**Comment by n0099** [comment]
> 白天模式也一样，这只是压了图吧？好像和变暗没关系
- 不要缩放：
> 测试图像需要像素精确显示。使用维基百科图片属性框和网络浏览器缩放 100%。
- 不要通过百度相册上传进行jpgq80压缩（但实际上无法避免因为十几年前贴吧就禁止直接hotlinking外部图片了）

**Comment by n0099** [comment]
> @xzxz520cs 夜间模式确实做了小图降低亮度
> 
> https://github.com/HuanCheng65/TiebaLite/blob/3ae3fcb96f854dcc5ad0b9c020a5504e0099ec61/app/src/main/java/com/huanchengfly/tieba/post/utils/ImageUtil.java#L496

但他日间模式下图也变暗

**Comment by xzxz520cs** [comment]
应该是我的表述不清楚，日间模式没有变暗的
