### ISSUE TITLE
帖子点赞会导致应用重启，自动返回动态页并刷新

### ISSUE THREAD

**Issue by zhtjtcz** [HuanCheng65/TiebaLite#159]
MIUI 12.5.7 系统，去年年初安装的 release 里的最新版，大约在去年年底、今年年初的时候，点赞功能出现了问题：每次点击右下角点赞按钮，会导致应用重新启动（看到启动页面），并自动刷新一下（上方出现更新 XX 条动态字样）。

**Comment by n0099** [comment]
> 去年年底、今年年初的时候

https://github.com/Starry-OvO/aiotieba/issues/64

**Comment by zhtjtcz** [comment]
在 TG 群里装上 4.0 版后不再有闪退情况发生了
