### ISSUE TITLE
支持删除单条搜索记录

### ISSUE THREAD

**Issue by 932749734** [HuanCheng65/TiebaLite#177]
关于搜索功能，不能删除单条记录，只能全部删除。以前的版本是可以长按单条记录删除的

**Comment by Runninginsilence1** [comment]
借楼，请问作者是在哪里更新测试版的啊？我看github的主页的release一直都是3.8的版本，请问作者还在更新吗？

**Comment by fankes** [comment]
@Runninginsilence1 切换分支

**Comment by Runninginsilence1** [comment]
谢谢之前在这里提醒了一下我的兄弟！不过为啥把回复给删了....
答案是切换git分支

**Comment by Runninginsilence1** [comment]
谢谢！不过为啥把回复给删了....

Fankesyooni ***@***.***> 于2023年5月6日周六 01:06写道：

**Comment by 932749734** [comment]
> 

切换一下就行

**Comment by i0799** [comment]
> 借楼，请问作者是在哪里更新测试版的啊？我看github的主页的release一直都是3.8的版本，请问作者还在更新吗？

同问！

**Comment by i0799** [comment]
已经下载了！

**Comment by zhangshenye** [comment]
> 已经下载了！

在哪切换啊，我切换完怎么还是3.8啊

**Comment by shuwei8626** [comment]
> > 已经下载了！
> 
> 在哪切换啊，我切换完怎么还是3.8啊

同问，这是要自己下载打包是吗

**Comment by shuwei8626** [comment]
找到了，在actions里面
