### ISSUE TITLE
大佬，方便做一个屏蔽视频的开关吗

### ISSUE THREAD

**Issue by yll690** [HuanCheng65/TiebaLite#183]
如题，现在出现的频率太高了，三四条里就有一个视频，真不想看那玩意儿

**Comment by WuJunkai2004** [comment]
设置里面不允许播放，不就可以了

**Comment by yll690** [comment]
不是播放问题，是动态里面出现视频的频率太高，而我不想让它出现。目前在用其他人的修改版，可以屏蔽动态里的视频了。

**Comment by HuanCheng65** [comment]
下版本计划新增隐藏视频贴功能
