### ISSUE TITLE
新版UI使用反馈

### ISSUE THREAD

**Issue by syw0618** [HuanCheng65/TiebaLite#188]
刚刚更新，目前发现两个需要优化的地方。一是在吧内浏览时上下滑动非常容易误触成左右滑动，希望可以调整左右滑动的触发阈值，减少误操作。二是看贴时看到帖子底部，继续上滑会先停顿一下然后才出现回弹动画，这个停顿看上去很不舒服。希望作者可以优化一下新UI的使用手感，谢谢。

**Comment by W15265725521** [comment]
> 刚刚更新，目前发现两个需要优化的地方。一是在吧内浏览时上下滑动非常容易误触成左右滑动，希望可以调整左右滑动的触发阈值，减少误操作。二是看贴时看到帖子底部，继续上滑会先停顿一下然后才出现回弹动画，这个停顿看上去很不舒服。希望作者可以优化一下新UI的使用手感，谢谢。

同意，上下滑几乎不能用

**Comment by HuanCheng65** [comment]
@W15265725521 马上发新版修复这个问题

**Comment by W15265725521** [comment]
> @W15265725521 马上发新版修复这个问题

好好好😍
