### ISSUE TITLE
【功能建议】关于新版UI的动态页的体验问题

### ISSUE THREAD

**Issue by kidbeans** [HuanCheng65/TiebaLite#191]
感觉新版ui的动态页加了关注和话滑梯分页固然很好，但实际刷帖子时（尤其是单手用时），除非完全垂直，很容易误触左右滑动，滑到关注吧友的帖子页面了😇不知道是不是我太笨了😭

**Comment by HuanCheng65** [comment]
@kidbeans 先更新到最新版
