### ISSUE TITLE
一个提示为[图片]的回复不可见

### ISSUE THREAD

**Issue by Jacobax** [HuanCheng65/TiebaLite#197]
![Screenshot_2023-08-07-15-12-52-338_com.huanchengfly.tieba.post-edit.jpg](https://github.com/HuanCheng65/TiebaLite/assets/23228895/60fdb1a6-46f2-4b81-8231-a563da0dfef2)

![Screenshot_2023-08-07-15-11-10-347_com.huanchengfly.tieba.post-edit.jpg](https://github.com/HuanCheng65/TiebaLite/assets/23228895/ecd1a027-334b-44bf-bea1-530a649cefc5)

**Comment by HuanCheng65** [comment]
贴吧现在支持楼中楼带图片了吗？
