### ISSUE TITLE
被封了

### ISSUE THREAD

**Issue by thirstywatch** [HuanCheng65/TiebaLite#198]
不听话，直接被封号了😭

**Comment by thirstywatch** [comment]
在贴吧lite里回帖会有概率被封号

**Comment by Wenti-D** [comment]
<img src="https://github.com/HuanCheng65/TiebaLite/assets/73067578/71373097-e75e-458a-9906-e18c05ecb3c7" width=400>

**Comment by thirstywatch** [comment]
> <img src="https://github.com/HuanCheng65/TiebaLite/assets/73067578/71373097-e75e-458a-9906-e18c05ecb3c7" width=400>

别笑，已经解封了😡

**Comment by ifhjl** [comment]
我现在下载的还是3年前的版本，请问在哪里可以下载新的版本呢？

**Comment by thirstywatch** [comment]
> 我现在下载的还是3年前的版本，请问在哪里可以下载新的版本呢？

在作者的群里

**Comment by pangu4720** [comment]
怎么加群

**Comment by thirstywatch** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
