### ISSUE TITLE
希望提供国内用户下载渠道！！

### ISSUE THREAD

**Issue by 1049731887** [HuanCheng65/TiebaLite#203]
比如在此处发布释放，蓝奏云盘 @ShellWen

**Comment by ShellWen** [comment]
Invalid Issues. Please close this Issues.
@HuanCheng65

**Comment by 1049731887** [comment]
> 无效问题。请关闭此问题。 @HuanCheng65

贴吧本来就是几乎全部的国内用户在用的

**Comment by WindSakura** [comment]
GayHub都上不去就憋下了XDD有夠水的

**Comment by History-exe** [comment]
你可以上GitHub，国外发布应该也没啥。
这东西本来就是灰色地带，多一些门槛隔绝某些有待心智成熟的人也好
