### ISSUE TITLE
关于新版ui滑动最下面加载更多的问题

### ISSUE THREAD

**Issue by 1846599447** [HuanCheng65/TiebaLite#208]
新版ui在动态页面或浏览帖子内容的时候，滑动到最下面并不会加载更多楼层，需要再次下拉触发松开才会加载，在帖子末尾也需要下拉才能看到有没有更多的楼层，甚至有时候需要下拉好几遍才能看清，这一点有点不如老版ui了，希望能够改进一下。

**Comment by HuanCheng65** [comment]
更改已经提交，下个版本就有了（
