### ISSUE TITLE
[BUG] “查看帖子”选项卡页面上下滑动，会右滑到“吧内精华”页面

### ISSUE THREAD

**Issue by C1og** [HuanCheng65/TiebaLite#218]
### 问题检查清单

- [X] 我已经阅读了[已知问题](https://github.com/HuanCheng65/TiebaLite/discussions/214)，并且确认该问题没有被列出。
- [X] 我确认该问题没有被其他人报告过。
- [X] 我确认正在使用最新版本。

### 问题描述

- 在“查看帖子”选项卡帖子列表页面上下滑动，有一定概率会误触发右滑到“吧内精华”页面
- 同理，在“吧内精华”上下滑动，会左滑到“查看帖子”

### 复现步骤

- 在“查看帖子”中，手指上滑、下滑且向右偏一点点后，立即按住（定住）屏幕
- 在“吧内精华”中，手指上滑、下滑且向做偏一点点后，立即按住（定住）屏幕

### 预期行为

在偏一点的上下滑动时，不滑动到“吧内精华”或“查看帖子”

### 实际行为

在偏一点的上下滑动时，滑动到了“吧内精华”或“查看帖子”页面

### 应用版本

4.0.0-alpha.16+34d6e12(390016)

### Android 版本

Android

### 设备型号

xperia 5ii

**Comment by n0099** [comment]
#191

**Comment by C1og** [comment]
已经是最新版本了，但问题还在在，不确定与 #191 是不是相同的bug

**Comment by HuanCheng65** [comment]
https://github.com/HuanCheng65/TiebaLite/assets/22636177/3f6e755a-5968-4584-bb5e-c1c545b95f71

我这里难以复现，麻烦提供下录屏

**Comment by C1og** [comment]
@HuanCheng65 更新到`resigned-release-4.0.0-beta.1+2885b2a.390100` 刷了 1小时，没遇到问题，好像修复了，感谢❤️
