### ISSUE TITLE
[BUG] 目标版本为安卓13及以上的贴吧lite在安卓13设备上无法在回帖中发送图片

### ISSUE THREAD

**Issue by Cyanide-zh** [HuanCheng65/TiebaLite#219]
### 问题检查清单

- [X] 我已经阅读了[已知问题](https://github.com/HuanCheng65/TiebaLite/discussions/214)，并且确认该问题没有被列出。
- [X] 我确认该问题没有被其他人报告过。
- [X] 我确认正在使用最新版本。

### 问题描述

4.0.0.-alpha 16 (此问题在之前那些适配了安卓13的版本上也出现),在安卓13设备上回复时无法在回帖中发送图片。

### 复现步骤

打开任意帖子选择回复,输入文字,点击图片,点击加号,选择图片

### 预期行为

在预览中看到图片缩略图,点击发送后正常发送。

### 实际行为

在预览中看到黑屏,点击发送后回帖中只有文字,没有图片。

### 截图或录屏

![此处已经添加了2张图片](https://github.com/HuanCheng65/TiebaLite/assets/111837046/62fd2bd5-dbb9-4e73-b417-73baf8d69da5)
此处已经添加了2张图片

### 应用版本

4.0.0.-alpha 16

### Android 版本

Android 13

### 设备型号

OnePlus 8 Pro、Xiaomi POCO F2 Pro

### 定制 UI 版本

crDroid 9.8, Android 13

**Comment by HuanCheng65** [comment]
旧版 UI 的相关问题不再处理，请使用新版 UI
