### ISSUE TITLE
输入框和键盘错位

### ISSUE THREAD

**Issue by forliuyifei** [HuanCheng65/TiebaLite#22]
![Screenshot_20201014-170609443](https://user-images.githubusercontent.com/53306807/96005893-81fe0880-0e6f-11eb-9b4e-e928228c4264.jpg)

不知道是不是由于手机隐藏了导航栏导致的，但在其它软件上没遇到这样的问题……整体下沉了

**Comment by visitor33426** [comment]
我也是这样的，调节键盘高度也不行
