### ISSUE TITLE
[BUG] 部分表情显示错误

### ISSUE THREAD

**Issue by PencilMario** [HuanCheng65/TiebaLite#221]
### 问题检查清单

- [X] 我已经阅读了[已知问题](https://github.com/HuanCheng65/TiebaLite/discussions/214)，并且确认该问题没有被列出。
- [X] 我确认该问题没有被其他人报告过。
- [X] 我确认正在使用最新版本。

### 问题描述

本应为XD的表情在tl里显示成了震惊

### 复现步骤

自己发帖子时，编辑时正常，发送出去后就会变成错误的
在官方贴吧里显示正常

### 预期行为

显示正确的表情

### 实际行为

表情不正确

### 截图或录屏

![4a332f8d794172c87e468136385c831](https://github.com/HuanCheng65/TiebaLite/assets/72117241/04f31f12-2335-40a6-b5f6-825098cb7f48)
![1d1d338e06fc025aff221cbe98ac324](https://github.com/HuanCheng65/TiebaLite/assets/72117241/b46d9b3b-39aa-42fa-8d4c-4b4d6acd3845)

### 应用版本

4.0.0-alpha.16+65af365

### Android 版本

Android 12

### 设备型号

红米K50

### 定制 UI 版本

MIUI 13.0.21

**Comment by HuanCheng65** [comment]
已知，已修复，等下版本更新
