### ISSUE TITLE
[BUG] 如果吧名太长会挡住返回键

### ISSUE THREAD

**Issue by xiqian2** [HuanCheng65/TiebaLite#232]
### 问题检查清单

- [X] 我已经阅读了[已知问题](https://github.com/HuanCheng65/TiebaLite/discussions/214)，并且确认该问题没有被列出。
- [X] 我确认该问题没有被其他人报告过。
- [X] 我确认正在使用最新版本。

### 问题描述

rt
![IMG_20231224_175728](https://github.com/HuanCheng65/TiebaLite/assets/117052180/0c6142f3-41c5-4288-ad24-2a34903cac2e)

### 复现步骤

打开https://tieba.baidu.com/f?kw=刚才去wc,没带纸,想把垃圾桶里的纸拿着擦,可是垃圾桶里没纸.就没擦
吧内任意帖子，如果屏幕不够长，就会挡住返回键

### 预期行为

返回键能显示

### 实际行为

返回键被吧名挡住

### 截图或录屏

https://github.com/HuanCheng65/TiebaLite/assets/117052180/cd7b8ba8-7531-4026-96ea-d5b0159b4819

### 应用版本

最新（23.12.24）

### Android 版本

Android 11

### 设备型号

OPPO reno

### 定制 UI 版本

color os 11.1

**Comment by xiqian2** [comment]
感恩

**Comment by n0099** [comment]
https://github.com/HuanCheng65/TiebaLite/commit/1761507ba38313b96eb8140b9042a708af52130a

**Comment by xiqian2** [comment]
> [1761507](https://github.com/HuanCheng65/TiebaLite/commit/1761507ba38313b96eb8140b9042a708af52130a)

就是因为我看见了才把这个issue关了呀😂
