### ISSUE TITLE
[Feature Request] 希望提供关闭发布评论的功能

### ISSUE THREAD

**Issue by History-exe** [HuanCheng65/TiebaLite#233]
### 描述

作为贴吧第三方客户端，通过本app发表评论会有风险，或许有用户干脆不发评论，只是浏览。

### 解决方案

对于这些用户，浏览帖子过程中，有时会误触，比如查看楼中楼评论，即使只是查看，也会弹出评论对话框，不想发评论的还需要手动关闭。

能否提供一个设置，干脆就给用户一个选择，直接关闭评论功能，提供一个纯粹的只浏览环境。

**Comment by n0099** [comment]
#192 
https://github.com/5ec1cff/my-notes/blob/8fde03d5031265a8c90df30ed823cc057e1014b2/ro-tieba.md
https://github.com/5ec1cff/RoTieba

**Comment by xiqian2** [comment]
设置-使用习惯-隐藏回帖入口？

**Comment by xiqian2** [comment]
> 设置-使用习惯-隐藏回帖入口？
如 ？

https://github.com/HuanCheng65/TiebaLite/assets/117052180/facc367b-9493-4516-a730-9dcae58545df

是有点糊，但没办法
