### ISSUE TITLE
[BUG] 帖子详情：查看更多回复 图片不显示

### ISSUE THREAD

**Issue by SlotSun** [HuanCheng65/TiebaLite#234]
### 问题检查清单

- [X] 我已经阅读了[已知问题](https://github.com/HuanCheng65/TiebaLite/discussions/214)，并且确认该问题没有被列出。
- [X] 我确认该问题没有被其他人报告过。
- [X] 我确认正在使用最新版本。

### 问题描述

带有图片的回复：点击“查看更多回复”->图片不显示（被替换为一个默认图片） 我自己跑了下代码 在 Android14虚拟机上就很正常

### 复现步骤

带有图片的回复：点击“查看更多回复”

### 预期行为

显示层主文字回复+图片回复

### 实际行为

带有图片的回复：点击“查看更多回复”->图片不显示（被替换为一个默认图片）

### 截图或录屏

![Screenshot_20240109_110616](https://github.com/HuanCheng65/TiebaLite/assets/20356305/be358c9b-0798-42cb-91f6-e14c0e47938a)
![Screenshot_20240109_110632](https://github.com/HuanCheng65/TiebaLite/assets/20356305/04cd1efe-7470-4715-bfb3-c3641802291e)

### 应用版本

4.0.0-alpha.16+ae92c10

### Android 版本

Android

### 设备型号

iQOO 12 PRO

### 定制 UI 版本

originOS 4 

### 其他信息

这个bug从上一部手机iQOO 5 安卓12 通过互传 安装到 iQOO 12 PRO安卓14 出现的

**Comment by n0099** [comment]
#230
