### ISSUE TITLE
作者大大你好，可以写一篇文章说明下贴吧api的请求过程吗，我也准备做一个flutter版本的贴吧

### ISSUE THREAD

**Issue by keluokeda** [HuanCheng65/TiebaLite#235]

**Comment by n0099** [comment]
https://github.com/Starry-OvO/aiotieba
https://github.com/HuanCheng65/TiebaLite/issues/233#issuecomment-1874352232

**Comment by HuanCheng65** [comment]
可以直接看友情链接里的 aiotieba（
https://github.com/Starry-OvO/aiotieba
