### ISSUE TITLE
[优化] 新UI卡出天际

### ISSUE THREAD

**Issue by Aunixtoyou** [HuanCheng65/TiebaLite#236]
### 问题检查清单

- [X] 我已经阅读了[已知问题](https://github.com/HuanCheng65/TiebaLite/discussions/214)，并且确认该问题没有被列出。
- [X] 我确认该问题没有被其他人报告过。
- [X] 我确认正在使用最新版本。

### 问题描述

主帖子列表和贴中回复列表加载滑动肉眼可见的卡顿

### 复现步骤

目前我使用IQOO11出行此问题

### 预期行为

能丝滑一点最好不过了

### 实际行为

入图所示，浅绿色（Measure / Layout）和墨绿色（Misc Time / VSync Delay）太过于耗时

### 截图或录屏

![Screenshot_20240131_110841](https://github.com/HuanCheng65/TiebaLite/assets/17799702/00a83eec-e56e-4ab2-884b-117890122de3)

### 应用版本

4.0-dev

### Android 版本

Android

### 设备型号

IQOO 11

**Comment by Aunixtoyou** [comment]
开启无图模式后要稍微好一点
![Screenshot_20240131_113559](https://github.com/HuanCheng65/TiebaLite/assets/17799702/13c0bcb1-6f8b-4d39-ae65-1dbea63ae2c3)

**Comment by HuanCheng65** [comment]
@Aunixtoyou 麻烦给出详细版本号

**Comment by Malus-risus** [comment]
Meizu 20pro, which is also powered by Snapdragon 8gen2, also encountered this problem.

I am use the lateast version([c503e92](https://github.com/HuanCheng65/TiebaLite/commit/c503e920d6b0ca9f2da375025b09ac6af18e7646))

**Comment by Aunixtoyou** [comment]
> @Aunixtoyou 麻烦给出详细版本号

分支版本 c503e920d6b0ca9f2da375025b09ac6af18e7646
手机cup 第二代骁龙8gen2    Android 14
