### ISSUE TITLE
[BUG] 安装了新版后直接闪退

### ISSUE THREAD

**Issue by xixilalaha** [HuanCheng65/TiebaLite#240]
### 问题检查清单

- [X] 我已经阅读了[已知问题](https://github.com/HuanCheng65/TiebaLite/discussions/214)，并且确认该问题没有被列出。
- [X] 我确认该问题没有被其他人报告过。
- [X] 我确认正在使用最新版本。

### 问题描述

打开软件直接闪退

### 复现步骤

安装后就直接打不开

### 预期行为

应该正常打开

### 实际行为

点击软件直接闪退，无法使用，重复多次后直接崩溃

### 截图或录屏

![6541706852561_ pic](https://github.com/HuanCheng65/TiebaLite/assets/35444255/8562e391-0d2a-4232-8441-6226014e90bc)

https://github.com/HuanCheng65/TiebaLite/assets/35444255/f54c36c2-8ecf-4219-ac63-40948a48c3ab

### 应用版本

4.0.0-alpha.16+ae92c10

### Android 版本

Android14

### 设备型号

三星s23 ultra

### 定制 UI 版本

One Ui6.0

**Comment by Liuzierjun** [comment]
同样问题，点击升级弹窗后无法打开应用

设备：红米K70 Pro

系统版本：Hyper OS 1.0.12.0  Android14

**Comment by HuanCheng65** [comment]
请更新到 Beta 1
