### ISSUE TITLE
[建议]魅族底栏问题

### ISSUE THREAD

**Issue by blmulang** [HuanCheng65/TiebaLite#25]
问题手机：魅族16S
问题：底栏挡住了回复框，可以更新个显示底栏吗？这样老是一按就返回了  0.0

![S01106-02003957](https://user-images.githubusercontent.com/48040829/98278984-51277400-1fd4-11eb-8439-3f6bf6df6f96.png)

**Comment by HuanCheng65** [comment]
魅族系统问题，无法修复

**Comment by HuanCheng65** [comment]
透明主题问题，后续修复
