### ISSUE TITLE
[BUG] 在使用浏览器的网页打开帖子时，无法跳转贴吧lite

### ISSUE THREAD

**Issue by harrylisen** [HuanCheng65/TiebaLite#250]
### 问题检查清单

- [X] 我已经阅读了[已知问题](https://github.com/HuanCheng65/TiebaLite/discussions/214)，并且确认该问题没有被列出。
- [X] 我确认该问题没有被其他人报告过。
- [X] 我确认正在使用最新版本。

### 问题描述

在浏览手机网页贴吧贴子时，点击百度贴吧内打开，无法跳转贴吧lite（之前的版本都是可以打开的）

### 复现步骤

于手机浏览器上打开任一贴子，点击打开app或者百度贴吧内打开

### 预期行为

跳转至贴吧lite浏览贴子

### 实际行为

浏览器提示打开华为应用市场

### 截图或录屏

![4F6E533D5BFBEA92AE314F12130FE4DF](https://github.com/HuanCheng65/TiebaLite/assets/46640121/e63e627e-1482-4e91-87cc-76be606bcf79)

### 应用版本

4.00—beta.1+2885b2a

### Android 版本

Android

### 设备型号

nova 7 pro

### 定制 UI 版本

鸿蒙4

**Comment by zst-z** [comment]
@harrylisen 没做链接跳转，等下个版本吧

**Comment by HuanCheng65** [comment]
检查是否为浏览器或系统默认设置问题

**Comment by zzy-ac** [comment]
> 检查是否为浏览器或系统默认设置问题

应该不是，之前的版本是可以正常跳转的
