### ISSUE TITLE
回帖失败，吧主开启神兽或该吧被严格监控，请输入验证码完成发帖

### ISSUE THREAD

**Issue by yijvyan** [HuanCheng65/TiebaLite#31]
![Screenshot_2021-01-02-23-11-05-910_com huanchengfly tieba post](https://user-images.githubusercontent.com/26464992/103460334-52fd8180-4d50-11eb-86b7-15398da9408b.jpg)

- [x] **没办法回复帖子，弹框要输入验证码，也没找见在哪里输入**

**Comment by HuanCheng65** [comment]
回贴部分不会再做修改，后续更新专注于看帖
