### ISSUE TITLE
能更新一下贴吧表情吗

### ISSUE THREAD

**Issue by MeltryllisServant** [HuanCheng65/TiebaLite#37]
新贴吧有不少表情感觉还挺形象好用的，希望可以更新进去

**Comment by HuanCheng65** [comment]
可以显示，但是不能发，后面会加入

**Comment by yijvyan** [comment]
表情确实太少了，需要加入一下了

**Comment by yijvyan** [comment]
> 可以显示，但是不能发，后面会加入

现在4.0版本显示的表情太小，希望可以调大一些。贴吧表情很形象，太小的话，就找不到那种感觉了
