### ISSUE TITLE
关于收藏帖子功能

### ISSUE THREAD

**Issue by AzureHanChen** [HuanCheng65/TiebaLite#40]
## 关于收藏功能
**版本 4.0.0.e924cb3.dev-2**
这个收藏功能有点迷  
刚进来帖子打算点个收藏，却显示移除收藏成功？？？  
此时五角星变为蓝色填充  
然后打开另一个贴吧APP后并没有发现该帖子  
然后我又点了一下收藏，五角星变为原先的填充色，但是却提示已添加收藏？

**Comment by HuanCheng65** [comment]
@AzureHanChen 更新
