### ISSUE TITLE
华为手机管家报a.gray.aimclickad威胁

### ISSUE THREAD

**Issue by sym233** [HuanCheng65/TiebaLite#44]
version: 3.8.3 release

os: emui 11.0.0, android 10

![image](https://user-images.githubusercontent.com/10321547/113431711-bc079a80-940e-11eb-9fb1-23007f01eeb1.png)

**Comment by HuanCheng65** [comment]
@sym233 误报，忽略即可

**Comment by 189169** [comment]
我的今天也莫名其妙误报了。不知道啥原因

**Comment by Jzrt** [comment]
三星也有

**Comment by Jzrt** [comment]
381没有

**Comment by KnIfER** [comment]
什么原因啊，是代码问题还是被加入了黑名单？

**Comment by HuanCheng65** [comment]
被国内的杀毒引擎误报了，忽略即可
