### ISSUE TITLE
不更新了？

### ISSUE THREAD

**Issue by CCRcmcpe** [HuanCheng65/TiebaLite#48]
求指路积极开发的fork或者其他客户端

**Comment by HuanCheng65** [comment]
仍在开发

**Comment by CCRcmcpe** [comment]
啊这，上一个commit还在去年八月底啊。加油吧，挺好用的。

**Comment by HuanCheng65** [comment]
@CCRcmcpe master分支是3.X版本，已经停止更新，4.0版本正在开发

**Comment by GodOfKiller** [comment]
@HuanCheng65 挺好用的，作者想问问4.0版本在哪里更新呀
