### ISSUE TITLE
建议：可以更改文件保存目录或者目录去掉空格

### ISSUE THREAD

**Issue by RikkaBlue** [HuanCheng65/TiebaLite#53]
部分应用没有做好相关方面的适配，遇到含空格目录后会发生错误，希望作者能够考虑改进一下。
非常感谢。

**Comment by RikkaBlue** [comment]
https://github.com/HuanCheng65/TiebaLite/blob/0c8e577f2c4992dc88a96512cb067b535c4d6349/app/src/main/java/com/huanchengfly/tieba/post/utils/FileUtil.java#L186
不知道能否直接更改这里的字段。

**Comment by pointm** [comment]
支持，想把图片保存在原来的贴吧图片文件夹里面，这样子就不需要重新去TieBaLite文件夹里看了

**Comment by HuanCheng65** [comment]
好的

**Comment by HuanCheng65** [comment]
已解决
