### ISSUE TITLE
app无法查看发送了“傻逼”的帖子

### ISSUE THREAD

**Issue by frisktale** [HuanCheng65/TiebaLite#62]
自从今日百度将“傻逼”和谐为图片后，所有带有“傻逼”的帖子均无法查看。  
如[傻逼好像不能发了](https://tieba.baidu.com/p/7538746907?see_lz=0)  
web端可以查看，但app查看会提示网络似乎有问题  
![Screenshot_20210914_210705](https://user-images.githubusercontent.com/21367674/133263136-86665b23-fed5-4493-b55f-ae7d4b6ae725.jpg)

**Comment by frisktale** [comment]
无论是使用3.8.3还是4.0 dev 5都会有这个问题

**Comment by zxzxwgh** [comment]
> 无论是使用3.8.3还是4.0 dev 5都会有这个问题

请问4.0在哪里下载或者更新？
