### ISSUE TITLE
查看帖子显示网络似乎有点问题

### ISSUE THREAD

**Issue by Qingtian-creat** [HuanCheng65/TiebaLite#65]
版本4.0.0.5fee614.dev-5，查看浏览帖子的时候老显示“网络似乎有点问题”，点进去看不了帖子，评论区是加载不出来的

**Comment by MarsTLBAD** [comment]
4.0的版本在哪下载的？作者不是只发布了去年的3.8.3版本吗？

**Comment by zxzxwgh** [comment]
> 版本4.0.0.5fee614.dev-5，查看浏览帖子的时候老显示“网络似乎有点问题”，点进去看不了帖子，评论区是加载不出来的

请问4.0版本在哪里更新

**Comment by pointm** [comment]
我的老版本看帖子也经常网络出现问题，不知道为什么

**Comment by woniao** [comment]
现在帖子里带“傻逼”二字的都不能看

**Comment by pointm** [comment]
我刚刚试了一下，百度好像抽风又可以看带傻逼的帖子了？？？
