### ISSUE TITLE
病毒报错规避请求

### ISSUE THREAD

**Issue by thehangedman12** [HuanCheng65/TiebaLite#78]
安装有病毒报告，这倒没啥。
但是安装后每次打开支付宝以及付款时候都会报告。手机是一加9r。
![Screenshot_2021-12-05-19-00-21-73_3915bacb930634b7e206116f9dc9486f.jpg](https://user-images.githubusercontent.com/69257813/144743809-0bfd1460-8a2c-469c-bded-797900735962.jpg)
![Screenshot_2021-12-05-18-59-15-49_bb8ece83317b06ec453d187d61792a56.jpg](https://user-images.githubusercontent.com/69257813/144743811-ef4b6276-7163-4e9f-a502-db44f1394635.jpg)

**Comment by Ipmlosion** [comment]
@thehangedman12 OnePlus没有白名单吗？

**Comment by thehangedman12** [comment]
> @thehangedman12 OnePlus没有白名单吗？

没有，只有省电模式的白名单。

**Comment by HuanCheng65** [comment]
4.0 更换了签名，已解决
