### ISSUE TITLE
搜索时切换搜帖子会闪退回主界面

### ISSUE THREAD

**Issue by detiam** [HuanCheng65/TiebaLite#80]
搜索文本“osu 数位板”然后切换到 搜贴 后会闪退到主界面
log：[001.log](https://github.com/HuanCheng65/TiebaLite/files/7740246/001.log)

**Comment by stanwsh** [comment]
同样遇到这个问题，只要点到搜贴就会闪退

**Comment by pointm** [comment]
这个问题现在也还有，搜贴吧不会有问题，搜贴子或者人概率闪退_(:з」∠)_

**Comment by detiam** [comment]
> 这个问题现在也还有，搜贴吧不会有问题，搜贴子或者人概率闪退_(:з」∠)_

你在README上点那个绿色PASSED，下载里面最新的自动构建搜贴不闪退，不过会一直提示更新

**Comment by pointm** [comment]
> > 这个问题现在也还有，搜贴吧不会有问题，搜贴子或者人概率闪退_(:з」∠)_
> 
> 你在README上点那个绿色PASSED，下载里面最新的自动构建搜贴不闪退，不过会一直提示更新

好哒，谢谢提醒，我马上就去康康

**Comment by pointm** [comment]
> > 这个问题现在也还有，搜贴吧不会有问题，搜贴子或者人概率闪退_(:з」∠)_
> 
> 你在README上点那个绿色PASSED，下载里面最新的自动构建搜贴不闪退，不过会一直提示更新

您好，我刚刚去试了一下，点进去之后就不知道该怎么操作了，请问能更加详细得说一说该怎么操作吗？_(:з」∠)_

**Comment by HuanCheng65** [comment]
已修复
