### ISSUE TITLE
内置的image picker似乎有问题

### ISSUE THREAD

**Issue by deorth-boffin** [HuanCheng65/TiebaLite#84]
默认进入全部后是正常显示的，但如果下拉选择其它文件夹后无法显示图片，此时就算选回全部也不能正常显示图片了。
![Screenshot_20220114-123201.png](https://user-images.githubusercontent.com/23164110/149451986-f7c554ff-f7b8-45e8-9e44-79a7df09b5ff.png)
这是十分明显的问题但没有其它人提issue，我猜这可能和机型有关？
测试机型：
Xperia 5 II Android 11
Chrome OS (94 96 97 98) Android Container 
我注意到主题贴发图使用的是System image picker，可否考虑回帖也使用系统的而不是内建的？

**Comment by HuanCheng65** [comment]
dev 8已修复
