### ISSUE TITLE
打开剪切板链接工作不正常

### ISSUE THREAD

**Issue by 5ec1cff** [HuanCheng65/TiebaLite#90]
测试环境：Android 11 WSA / MIUI 12.5 Android 11
测试版本：4.0 Dev-7

只有打开图片 / 点击回帖的时候询问是否打开剪贴板的链接，并且只要剪贴板存在链接，则**总是询问**。

![WsaClient_JRhBmTVPPj](https://user-images.githubusercontent.com/56485584/154788384-288b424c-6377-471e-9c25-cd697b3008b5.gif)

根据源码，检测剪贴板链接的时机是 onResume ，但实测发现，大部分情况下无法访问剪贴板，可能是 Android 10 开始对应用获取剪贴板的限制导致。

![image](https://user-images.githubusercontent.com/56485584/154788416-3366ddf3-897d-4ef7-a4c3-b8feb87351dc.png)
![image](https://user-images.githubusercontent.com/56485584/154788438-e0712e58-c59b-49c9-b327-3ad2f3d79f04.png)

补充：使用 clipboard-whitelist 允许访问剪贴板后，随便打开一个 Activity 都会询问了……

**Comment by HuanCheng65** [comment]
已修复
